// MAIN-world content script — runs in the YouTube PAGE's JS context at
// document_start. It exists for ONE reason: in 2025/26 YouTube requires a valid
// `pot` (Proof-of-Origin) token on caption requests. A direct fetch of
// `captionTracks[].baseUrl` (or the public /api/timedtext endpoint) now returns
// HTTP 200 with an EMPTY body without that token — which is why every prior
// caption layer broke. The token is generated by YouTube's own BotGuard in the
// page; we cannot mint it ourselves. So instead we OBSERVE the player's own
// network traffic (which carries a valid pot) by monkey-patching fetch + XHR
// here in the MAIN world, and relay what we see to the ISOLATED content script
// via a DOM CustomEvent. No chrome.* APIs are available in the MAIN world.
//
// Sources for the pot requirement: yt-dlp PO Token Guide + issues #13075/#13443.

const EVENT = "echoly:yt-capture";
const TIMEDTEXT_RE = /\/api\/timedtext\?/;
const PLAYER_RE = /\/youtubei\/v1\/player(\?|$)/;

function emit(payload: unknown): void {
  try {
    document.dispatchEvent(
      new CustomEvent(EVENT, { detail: JSON.stringify(payload) }),
    );
  } catch {
    /* ignore */
  }
}

function handlePlayerBody(text: string): void {
  let json: Record<string, unknown> | undefined;
  try {
    json = JSON.parse(text);
  } catch {
    return;
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const j = json as any;
  const tracks =
    j?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  // poToken can live in a couple of spots depending on client/version.
  const poToken =
    j?.captions?.playerCaptionsTracklistRenderer?.serviceIntegrityDimensions
      ?.poToken ?? j?.serviceIntegrityDimensions?.poToken;
  const videoId = j?.videoDetails?.videoId;
  if (Array.isArray(tracks) && tracks.length) {
    emit({
      kind: "player",
      videoId,
      poToken,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      captionTracks: (tracks as any[]).map((t) => ({
        baseUrl: t?.baseUrl,
        languageCode: t?.languageCode,
        kind: t?.kind,
      })),
    });
  }
}

function inspect(url: string, getText: () => Promise<string>): void {
  try {
    if (TIMEDTEXT_RE.test(url)) {
      // The player's OWN timedtext request — its URL carries a valid pot +
      // signature. Relaying the URL lets the isolated world refetch it (or just
      // reuse it). We also relay the body so captions can be parsed with zero
      // refetch (fully pot-proof).
      emit({ kind: "cc-url", url });
      void getText()
        .then((body) => {
          if (body) emit({ kind: "cc-body", url, body });
        })
        .catch(() => {});
    } else if (PLAYER_RE.test(url)) {
      void getText().then(handlePlayerBody).catch(() => {});
    }
  } catch {
    /* ignore */
  }
}

function installHooks(): void {
  // ── fetch ──────────────────────────────────────────────────────────────
  const origFetch = window.fetch;
  if (typeof origFetch === "function") {
    window.fetch = function (
      this: typeof window,
      ...args: Parameters<typeof fetch>
    ): Promise<Response> {
      const input = args[0];
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.href
            : input instanceof Request
              ? input.url
              : String(input);
      const p = origFetch.apply(this, args);
      if (url && (TIMEDTEXT_RE.test(url) || PLAYER_RE.test(url))) {
        p.then((res) => {
          inspect(url, () => res.clone().text());
        }).catch(() => {});
      }
      return p;
    };
  }

  // ── XMLHttpRequest ─────────────────────────────────────────────────────
  const XHR = XMLHttpRequest.prototype;
  const origOpen = XHR.open;
  const origSend = XHR.send;
  XHR.open = function (
    this: XMLHttpRequest,
    method: string,
    url: string | URL,
    ...rest: unknown[]
  ): void {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (this as any).__echolyUrl = typeof url === "string" ? url : url.href;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return (origOpen as any).call(this, method, url, ...rest);
  };
  XHR.send = function (
    this: XMLHttpRequest,
    ...args: unknown[]
  ): void {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const url = (this as any).__echolyUrl as string | undefined;
    if (url && (TIMEDTEXT_RE.test(url) || PLAYER_RE.test(url))) {
      this.addEventListener("load", () => {
        inspect(url, async () => this.responseText);
      });
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return (origSend as any).apply(this, args);
  };
}

export default defineContentScript({
  matches: ["https://*.youtube.com/*", "https://youtube.com/*"],
  runAt: "document_start",
  world: "MAIN",
  main() {
    installHooks();
  },
});
